HOME_DIR = '' # eg. '/home/yourusername/'
SRC_DIR = HOME_DIR+'imagenet_experiments/'
SCRATCH_DIR = HOME_DIR+'data/'
IMAGENET_DIR = SCRATCH_DIR+'imagenet/'

# VALIDATION CONSTANTS
DATA_DIR = IMAGENET_DIR+'data/validation/'
OUT_DIR = IMAGENET_DIR+'out/validation/'
CHECKPOINTS_DIR = SRC_DIR+'models/weights/'
VALIDATIONSET_RECORDS_EXPRESSION = DATA_DIR+'validation-*'
VALIDATIONSET_RECORDS_SHARD_EXPRESSION = DATA_DIR+'validation-00%03d-of-00128'
NUM_SAMPLES_VALIDATIONSET = 50000
ADVERSARIAL_OUT_DIR = OUT_DIR+'adversarial/'
PREPROCESSED_OUT_DIR = OUT_DIR+'preprocessed/'
EVAL_OUT_DIR = OUT_DIR + 'eval/'
L2_OUT_DIR = OUT_DIR + 'l2norm/'
TOP_K_EVAL_DIR = OUT_DIR + 'top_k/'

# TRAINING CONSTANTS
TRAIN_RECORDS_DIR = IMAGENET_DIR+'data/train/'
TRAINED_MODELS_DIR = IMAGENET_DIR+'training/'
